[package]
name = "x-flipper-360"
version = "0.1.0"
edition = "2021"

[dependencies]
dds = { git = "https://github.com/offsetting/dds" }
modular-bitfield = "0.11"
binrw = "0.8"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
